version: ''
networks:
  bridge:
    driver: bridge
services:
  web:
    image: "xwiki:lts-mysql-tomcat"
    container_name: xwiki-web
    depends_on:
      - db
      - index
    ports:
      - "8080:8080"
    environment:
      - XWIKI_VERSION=xwiki
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_DATABASE=xwiki
      - DB_HOST=xwiki-db
      - INDEX_HOST=xwiki-index
      - JAVA_OPTS=-javaagent:/opt/agent/glowroot-0.13.6-dist/glowroot/glowroot.jar
    volumes:
      - xwiki-data:/usr/local/xwiki
      - ./files:/opt/agent
    depends_on:
      - glowroot-central
    networks:
      - bridge
  db:
    image: "mysql:5.7"
    container_name: xwiki-db
    volumes:
      - ./mysql/xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    networks:
      - bridge
  index:
    image: "solr:7.2"
    container_name: xwiki-index
    volumes:
      - ./solr:/docker-entrypoint-initdb.d
      - solr-data:/opt/solr/server/solr
    networks:
      - bridge
  glowroot-central-db:
    container_name: glowroot-central-db
    image: cassandra
    volumes:
      - cassandra:/var/lib/cassandra
    restart: always
    networks:
     - bridge
  glowroot-central:
    container_name: glowroot-central-server
    image: gagoukun/glowroot-central:0.13.6-2
    ports:
      - "0.0.0.0:4000:4000"
      - "0.0.0.0:8181:8181"
    links:
      - glowroot-central-db:cassandra
    depends_on:
      - glowroot-central-db
    restart: always
    networks:
      - bridge
volumes:
  cassandra: {}
  mysql-data: {}
  xwiki-data: {}
  solr-data: {}
